CREATE TABLE IF NOT EXISTS Users(
	id INT UNSIGNED AUTO_INCREMENT,
	email VARCHAR(40) NOT NULL UNIQUE,
	password VARCHAR(60) NOT NULL,
	PRIMARY KEY (id)
)
CHARACTER SET 'utf8'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Profils(
	id INT UNSIGNED AUTO_INCREMENT,
	firtName VARCHAR(40) NOT NULL,
	lastName VARCHAR(40) NOT NULL,
	picture VARCHAR(128) ,
	friends VARCHAR(255) DEFAULT '[]',
	user_id INT UNSIGNED NOT NULL,
	created_date DATETIME NOT NULL,
	PRIMARY KEY (id)
)
CHARACTER SET 'utf8'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Posts(
	id INT UNSIGNED AUTO_INCREMENT,
	title VARCHAR(40),
	description VARCHAR(255) NOT NULL,
	media VARCHAR(255),
	likes VARCHAR(255) DEFAULT '[]',
	dislikes VARCHAR(255) DEFAULT '[]',
	profil_id INT UNSIGNED,
	posted_date DATETIME NOT NULL,
	PRIMARY KEY (id)
)
CHARACTER SET 'utf8'
ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Comments(
	id INT UNSIGNED AUTO_INCREMENT,
	comment_text VARCHAR(255) NOT NULL,
	likes VARCHAR(255) DEFAULT '[]',
	dislikes VARCHAR(255) DEFAULT '[]',
	post_id INT UNSIGNED  NOT NULL,
	profil_id INT UNSIGNED,
	comment_date DATETIME NOT NULL,
	PRIMARY KEY (id)
)
CHARACTER SET 'utf8'
ENGINE=InnoDB;

ALTER TABLE Profils
ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE;

ALTER TABLE Posts
ADD CONSTRAINT fk_post_profil_id FOREIGN KEY (profil_id) REFERENCES Profils(id) ON DELETE CASCADE;

ALTER TABLE Comments
ADD CONSTRAINT fk_post_id FOREIGN KEY (post_id) REFERENCES Posts(id) ON DELETE CASCADE;

ALTER TABLE Comments
ADD CONSTRAINT fk_comment_profil_id FOREIGN KEY (profil_id) REFERENCES Profils(id) ON DELETE CASCADE;